carpole:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10000

  # Position Controllers ---------------------------------------
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: bar_car
    pid: {p: 0.0, i: 0.0, d: 0.0}

  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: carsld
    # pid: {p: 10.0, i: 0.0, d: 0.0}
